FROM python:3.10.6

RUN useradd --user-group --system --create-home --no-log-init user
USER user
ENV PATH=/home/user/.local/bin:$PATH

WORKDIR /home/user/
COPY --chown=user:user ./code ./code/
RUN python -m pip install --upgrade pip && \
	pip install -r code/requirements.txt

WORKDIR /home/user/code
CMD ["uvicorn", "main:app","--host", "0.0.0.0"]